/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import 'sgb9-components';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SiteHeader {}
  interface SiteHeaderAttributes extends StencilHTMLAttributes {}

  interface ElanHome {
    'history': RouterHistory;
  }
  interface ElanHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ElanPage {
    'history': RouterHistory;
  }
  interface ElanPageAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ElanProfile {
    'match': MatchResults;
  }
  interface ElanProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface ElanProfile1 {
    'history': RouterHistory;
  }
  interface ElanProfile1Attributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ElanRoot {}
  interface ElanRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SiteHeader': Components.SiteHeader;
    'ElanHome': Components.ElanHome;
    'ElanPage': Components.ElanPage;
    'ElanProfile': Components.ElanProfile;
    'ElanProfile1': Components.ElanProfile1;
    'ElanRoot': Components.ElanRoot;
  }

  interface StencilIntrinsicElements {
    'site-header': Components.SiteHeaderAttributes;
    'elan-home': Components.ElanHomeAttributes;
    'elan-page': Components.ElanPageAttributes;
    'elan-profile': Components.ElanProfileAttributes;
    'elan-profile1': Components.ElanProfile1Attributes;
    'elan-root': Components.ElanRootAttributes;
  }


  interface HTMLSiteHeaderElement extends Components.SiteHeader, HTMLStencilElement {}
  var HTMLSiteHeaderElement: {
    prototype: HTMLSiteHeaderElement;
    new (): HTMLSiteHeaderElement;
  };

  interface HTMLElanHomeElement extends Components.ElanHome, HTMLStencilElement {}
  var HTMLElanHomeElement: {
    prototype: HTMLElanHomeElement;
    new (): HTMLElanHomeElement;
  };

  interface HTMLElanPageElement extends Components.ElanPage, HTMLStencilElement {}
  var HTMLElanPageElement: {
    prototype: HTMLElanPageElement;
    new (): HTMLElanPageElement;
  };

  interface HTMLElanProfileElement extends Components.ElanProfile, HTMLStencilElement {}
  var HTMLElanProfileElement: {
    prototype: HTMLElanProfileElement;
    new (): HTMLElanProfileElement;
  };

  interface HTMLElanProfile1Element extends Components.ElanProfile1, HTMLStencilElement {}
  var HTMLElanProfile1Element: {
    prototype: HTMLElanProfile1Element;
    new (): HTMLElanProfile1Element;
  };

  interface HTMLElanRootElement extends Components.ElanRoot, HTMLStencilElement {}
  var HTMLElanRootElement: {
    prototype: HTMLElanRootElement;
    new (): HTMLElanRootElement;
  };

  interface HTMLElementTagNameMap {
    'site-header': HTMLSiteHeaderElement
    'elan-home': HTMLElanHomeElement
    'elan-page': HTMLElanPageElement
    'elan-profile': HTMLElanProfileElement
    'elan-profile1': HTMLElanProfile1Element
    'elan-root': HTMLElanRootElement
  }

  interface ElementTagNameMap {
    'site-header': HTMLSiteHeaderElement;
    'elan-home': HTMLElanHomeElement;
    'elan-page': HTMLElanPageElement;
    'elan-profile': HTMLElanProfileElement;
    'elan-profile1': HTMLElanProfile1Element;
    'elan-root': HTMLElanRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
