/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import 'sgb9-components';
import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface Sgb9Input1 {
    'force': boolean;
    'getHelpState': () => Promise<boolean>;
    'helpId': string;
    'idValue': string;
    'isHilfeAn': boolean;
    'label': string;
    'name': string;
    'setHelpId': (hilfeId: string) => void;
  }
  interface Sgb9Input1Attributes extends StencilHTMLAttributes {
    'force'?: boolean;
    'getHelpState'?: () => Promise<boolean>;
    'helpId'?: string;
    'idValue'?: string;
    'isHilfeAn'?: boolean;
    'label'?: string;
    'name'?: string;
    'setHelpId'?: (hilfeId: string) => void;
  }

  interface Sgb9Input {
    'force': boolean;
    'helpId': string;
    'idValue': string;
    'isHilfeAn': boolean;
    'label': string;
    'name': string;
  }
  interface Sgb9InputAttributes extends StencilHTMLAttributes {
    'force'?: boolean;
    'helpId'?: string;
    'idValue'?: string;
    'isHilfeAn'?: boolean;
    'label'?: string;
    'name'?: string;
    'onSetNewHelp'?: (event: CustomEvent) => void;
  }

  interface ElanHilfe {
    'hilfeIdValue': string;
  }
  interface ElanHilfeAttributes extends StencilHTMLAttributes {
    'hilfeIdValue'?: string;
  }

  interface SiteHeader {}
  interface SiteHeaderAttributes extends StencilHTMLAttributes {
    'onCheckHilfeChange'?: (event: CustomEvent) => void;
  }

  interface ElanHome {
    'history': RouterHistory;
  }
  interface ElanHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ElanPage {
    'getHelpState': () => Promise<boolean>;
    'history': RouterHistory;
    'isHilfeAn': boolean;
    'setHelpId': (hilfeId: string) => void;
  }
  interface ElanPageAttributes extends StencilHTMLAttributes {
    'getHelpState'?: () => Promise<boolean>;
    'history'?: RouterHistory;
    'isHilfeAn'?: boolean;
    'setHelpId'?: (hilfeId: string) => void;
  }

  interface ElanProfile {
    'match': MatchResults;
  }
  interface ElanProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface ElanProfile1 {
    'history': RouterHistory;
  }
  interface ElanProfile1Attributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ElanRoot {}
  interface ElanRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'Sgb9Input1': Components.Sgb9Input1;
    'Sgb9Input': Components.Sgb9Input;
    'ElanHilfe': Components.ElanHilfe;
    'SiteHeader': Components.SiteHeader;
    'ElanHome': Components.ElanHome;
    'ElanPage': Components.ElanPage;
    'ElanProfile': Components.ElanProfile;
    'ElanProfile1': Components.ElanProfile1;
    'ElanRoot': Components.ElanRoot;
  }

  interface StencilIntrinsicElements {
    'sgb9-input1': Components.Sgb9Input1Attributes;
    'sgb9-input': Components.Sgb9InputAttributes;
    'elan-hilfe': Components.ElanHilfeAttributes;
    'site-header': Components.SiteHeaderAttributes;
    'elan-home': Components.ElanHomeAttributes;
    'elan-page': Components.ElanPageAttributes;
    'elan-profile': Components.ElanProfileAttributes;
    'elan-profile1': Components.ElanProfile1Attributes;
    'elan-root': Components.ElanRootAttributes;
  }


  interface HTMLSgb9Input1Element extends Components.Sgb9Input1, HTMLStencilElement {}
  var HTMLSgb9Input1Element: {
    prototype: HTMLSgb9Input1Element;
    new (): HTMLSgb9Input1Element;
  };

  interface HTMLSgb9InputElement extends Components.Sgb9Input, HTMLStencilElement {}
  var HTMLSgb9InputElement: {
    prototype: HTMLSgb9InputElement;
    new (): HTMLSgb9InputElement;
  };

  interface HTMLElanHilfeElement extends Components.ElanHilfe, HTMLStencilElement {}
  var HTMLElanHilfeElement: {
    prototype: HTMLElanHilfeElement;
    new (): HTMLElanHilfeElement;
  };

  interface HTMLSiteHeaderElement extends Components.SiteHeader, HTMLStencilElement {}
  var HTMLSiteHeaderElement: {
    prototype: HTMLSiteHeaderElement;
    new (): HTMLSiteHeaderElement;
  };

  interface HTMLElanHomeElement extends Components.ElanHome, HTMLStencilElement {}
  var HTMLElanHomeElement: {
    prototype: HTMLElanHomeElement;
    new (): HTMLElanHomeElement;
  };

  interface HTMLElanPageElement extends Components.ElanPage, HTMLStencilElement {}
  var HTMLElanPageElement: {
    prototype: HTMLElanPageElement;
    new (): HTMLElanPageElement;
  };

  interface HTMLElanProfileElement extends Components.ElanProfile, HTMLStencilElement {}
  var HTMLElanProfileElement: {
    prototype: HTMLElanProfileElement;
    new (): HTMLElanProfileElement;
  };

  interface HTMLElanProfile1Element extends Components.ElanProfile1, HTMLStencilElement {}
  var HTMLElanProfile1Element: {
    prototype: HTMLElanProfile1Element;
    new (): HTMLElanProfile1Element;
  };

  interface HTMLElanRootElement extends Components.ElanRoot, HTMLStencilElement {}
  var HTMLElanRootElement: {
    prototype: HTMLElanRootElement;
    new (): HTMLElanRootElement;
  };

  interface HTMLElementTagNameMap {
    'sgb9-input1': HTMLSgb9Input1Element
    'sgb9-input': HTMLSgb9InputElement
    'elan-hilfe': HTMLElanHilfeElement
    'site-header': HTMLSiteHeaderElement
    'elan-home': HTMLElanHomeElement
    'elan-page': HTMLElanPageElement
    'elan-profile': HTMLElanProfileElement
    'elan-profile1': HTMLElanProfile1Element
    'elan-root': HTMLElanRootElement
  }

  interface ElementTagNameMap {
    'sgb9-input1': HTMLSgb9Input1Element;
    'sgb9-input': HTMLSgb9InputElement;
    'elan-hilfe': HTMLElanHilfeElement;
    'site-header': HTMLSiteHeaderElement;
    'elan-home': HTMLElanHomeElement;
    'elan-page': HTMLElanPageElement;
    'elan-profile': HTMLElanProfileElement;
    'elan-profile1': HTMLElanProfile1Element;
    'elan-root': HTMLElanRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
